// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.1
// source: service.proto

package cloud_user_center

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CloudUserCenterClient is the client API for CloudUserCenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CloudUserCenterClient interface {
	// 创建用户
	UserInfoCreate(ctx context.Context, in *UserInfoCreateRequest, opts ...grpc.CallOption) (*UserInfoCreateResponse, error)
	// 登录校验
	UserInfoAuth(ctx context.Context, in *UserInfoAuthRequest, opts ...grpc.CallOption) (*UserInfoAuthResponse, error)
	// 更新用户信息
	UserInfoUpdate(ctx context.Context, in *UserInfoUpdateRequest, opts ...grpc.CallOption) (*UserInfoUpdateResponse, error)
	// 删除用户
	UserInfoDelete(ctx context.Context, in *UserInfoDeleteRequest, opts ...grpc.CallOption) (*UserInfoDeleteResponse, error)
	// 获取用户信息
	UserInfoGet(ctx context.Context, in *UserInfoGetRequest, opts ...grpc.CallOption) (*UserInfoGetResponse, error)
	// 批量获取用户信息
	MUserInfoGet(ctx context.Context, in *MUserInfoGetRequest, opts ...grpc.CallOption) (*MUserInfoGetResponse, error)
	// 根据用户名获取用户信息
	UserInfoGetByName(ctx context.Context, in *UserInfoGetByNameRequest, opts ...grpc.CallOption) (*UserInfoGetByNameResponse, error)
	// 搜索用户信息
	UserInfoSearch(ctx context.Context, in *UserInfoSearchRequest, opts ...grpc.CallOption) (*UserInfoSearchResponse, error)
	// 创建用户消息
	UserMessageCreate(ctx context.Context, in *UserMessageCreateRequest, opts ...grpc.CallOption) (*UserMessageCreateResponse, error)
	// 批量创建用户消息
	MUserMessageCreate(ctx context.Context, in *MUserMessageCreateRequest, opts ...grpc.CallOption) (*MUserMessageCreateResponse, error)
	// 用户消息列表
	UserMessageList(ctx context.Context, in *UserMessageListRequest, opts ...grpc.CallOption) (*UserMessageListResponse, error)
	// 用户消息获取
	UserMessageGet(ctx context.Context, in *UserMessageGetRequest, opts ...grpc.CallOption) (*UserMessageGetResponse, error)
	// 用户消息更新
	UserMessageUpdate(ctx context.Context, in *UserMessageUpdateRequest, opts ...grpc.CallOption) (*UserMessageUpdateResponse, error)
	// 用户消息删除
	UserMessageDelete(ctx context.Context, in *UserMessageDeleteRequest, opts ...grpc.CallOption) (*UserMessageDeleteResponse, error)
}

type cloudUserCenterClient struct {
	cc grpc.ClientConnInterface
}

func NewCloudUserCenterClient(cc grpc.ClientConnInterface) CloudUserCenterClient {
	return &cloudUserCenterClient{cc}
}

func (c *cloudUserCenterClient) UserInfoCreate(ctx context.Context, in *UserInfoCreateRequest, opts ...grpc.CallOption) (*UserInfoCreateResponse, error) {
	out := new(UserInfoCreateResponse)
	err := c.cc.Invoke(ctx, "/cloud_user_center.CloudUserCenter/UserInfoCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudUserCenterClient) UserInfoAuth(ctx context.Context, in *UserInfoAuthRequest, opts ...grpc.CallOption) (*UserInfoAuthResponse, error) {
	out := new(UserInfoAuthResponse)
	err := c.cc.Invoke(ctx, "/cloud_user_center.CloudUserCenter/UserInfoAuth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudUserCenterClient) UserInfoUpdate(ctx context.Context, in *UserInfoUpdateRequest, opts ...grpc.CallOption) (*UserInfoUpdateResponse, error) {
	out := new(UserInfoUpdateResponse)
	err := c.cc.Invoke(ctx, "/cloud_user_center.CloudUserCenter/UserInfoUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudUserCenterClient) UserInfoDelete(ctx context.Context, in *UserInfoDeleteRequest, opts ...grpc.CallOption) (*UserInfoDeleteResponse, error) {
	out := new(UserInfoDeleteResponse)
	err := c.cc.Invoke(ctx, "/cloud_user_center.CloudUserCenter/UserInfoDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudUserCenterClient) UserInfoGet(ctx context.Context, in *UserInfoGetRequest, opts ...grpc.CallOption) (*UserInfoGetResponse, error) {
	out := new(UserInfoGetResponse)
	err := c.cc.Invoke(ctx, "/cloud_user_center.CloudUserCenter/UserInfoGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudUserCenterClient) MUserInfoGet(ctx context.Context, in *MUserInfoGetRequest, opts ...grpc.CallOption) (*MUserInfoGetResponse, error) {
	out := new(MUserInfoGetResponse)
	err := c.cc.Invoke(ctx, "/cloud_user_center.CloudUserCenter/MUserInfoGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudUserCenterClient) UserInfoGetByName(ctx context.Context, in *UserInfoGetByNameRequest, opts ...grpc.CallOption) (*UserInfoGetByNameResponse, error) {
	out := new(UserInfoGetByNameResponse)
	err := c.cc.Invoke(ctx, "/cloud_user_center.CloudUserCenter/UserInfoGetByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudUserCenterClient) UserInfoSearch(ctx context.Context, in *UserInfoSearchRequest, opts ...grpc.CallOption) (*UserInfoSearchResponse, error) {
	out := new(UserInfoSearchResponse)
	err := c.cc.Invoke(ctx, "/cloud_user_center.CloudUserCenter/UserInfoSearch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudUserCenterClient) UserMessageCreate(ctx context.Context, in *UserMessageCreateRequest, opts ...grpc.CallOption) (*UserMessageCreateResponse, error) {
	out := new(UserMessageCreateResponse)
	err := c.cc.Invoke(ctx, "/cloud_user_center.CloudUserCenter/UserMessageCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudUserCenterClient) MUserMessageCreate(ctx context.Context, in *MUserMessageCreateRequest, opts ...grpc.CallOption) (*MUserMessageCreateResponse, error) {
	out := new(MUserMessageCreateResponse)
	err := c.cc.Invoke(ctx, "/cloud_user_center.CloudUserCenter/MUserMessageCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudUserCenterClient) UserMessageList(ctx context.Context, in *UserMessageListRequest, opts ...grpc.CallOption) (*UserMessageListResponse, error) {
	out := new(UserMessageListResponse)
	err := c.cc.Invoke(ctx, "/cloud_user_center.CloudUserCenter/UserMessageList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudUserCenterClient) UserMessageGet(ctx context.Context, in *UserMessageGetRequest, opts ...grpc.CallOption) (*UserMessageGetResponse, error) {
	out := new(UserMessageGetResponse)
	err := c.cc.Invoke(ctx, "/cloud_user_center.CloudUserCenter/UserMessageGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudUserCenterClient) UserMessageUpdate(ctx context.Context, in *UserMessageUpdateRequest, opts ...grpc.CallOption) (*UserMessageUpdateResponse, error) {
	out := new(UserMessageUpdateResponse)
	err := c.cc.Invoke(ctx, "/cloud_user_center.CloudUserCenter/UserMessageUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudUserCenterClient) UserMessageDelete(ctx context.Context, in *UserMessageDeleteRequest, opts ...grpc.CallOption) (*UserMessageDeleteResponse, error) {
	out := new(UserMessageDeleteResponse)
	err := c.cc.Invoke(ctx, "/cloud_user_center.CloudUserCenter/UserMessageDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CloudUserCenterServer is the server API for CloudUserCenter service.
// All implementations must embed UnimplementedCloudUserCenterServer
// for forward compatibility
type CloudUserCenterServer interface {
	// 创建用户
	UserInfoCreate(context.Context, *UserInfoCreateRequest) (*UserInfoCreateResponse, error)
	// 登录校验
	UserInfoAuth(context.Context, *UserInfoAuthRequest) (*UserInfoAuthResponse, error)
	// 更新用户信息
	UserInfoUpdate(context.Context, *UserInfoUpdateRequest) (*UserInfoUpdateResponse, error)
	// 删除用户
	UserInfoDelete(context.Context, *UserInfoDeleteRequest) (*UserInfoDeleteResponse, error)
	// 获取用户信息
	UserInfoGet(context.Context, *UserInfoGetRequest) (*UserInfoGetResponse, error)
	// 批量获取用户信息
	MUserInfoGet(context.Context, *MUserInfoGetRequest) (*MUserInfoGetResponse, error)
	// 根据用户名获取用户信息
	UserInfoGetByName(context.Context, *UserInfoGetByNameRequest) (*UserInfoGetByNameResponse, error)
	// 搜索用户信息
	UserInfoSearch(context.Context, *UserInfoSearchRequest) (*UserInfoSearchResponse, error)
	// 创建用户消息
	UserMessageCreate(context.Context, *UserMessageCreateRequest) (*UserMessageCreateResponse, error)
	// 批量创建用户消息
	MUserMessageCreate(context.Context, *MUserMessageCreateRequest) (*MUserMessageCreateResponse, error)
	// 用户消息列表
	UserMessageList(context.Context, *UserMessageListRequest) (*UserMessageListResponse, error)
	// 用户消息获取
	UserMessageGet(context.Context, *UserMessageGetRequest) (*UserMessageGetResponse, error)
	// 用户消息更新
	UserMessageUpdate(context.Context, *UserMessageUpdateRequest) (*UserMessageUpdateResponse, error)
	// 用户消息删除
	UserMessageDelete(context.Context, *UserMessageDeleteRequest) (*UserMessageDeleteResponse, error)
	mustEmbedUnimplementedCloudUserCenterServer()
}

// UnimplementedCloudUserCenterServer must be embedded to have forward compatible implementations.
type UnimplementedCloudUserCenterServer struct {
}

func (UnimplementedCloudUserCenterServer) UserInfoCreate(context.Context, *UserInfoCreateRequest) (*UserInfoCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserInfoCreate not implemented")
}
func (UnimplementedCloudUserCenterServer) UserInfoAuth(context.Context, *UserInfoAuthRequest) (*UserInfoAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserInfoAuth not implemented")
}
func (UnimplementedCloudUserCenterServer) UserInfoUpdate(context.Context, *UserInfoUpdateRequest) (*UserInfoUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserInfoUpdate not implemented")
}
func (UnimplementedCloudUserCenterServer) UserInfoDelete(context.Context, *UserInfoDeleteRequest) (*UserInfoDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserInfoDelete not implemented")
}
func (UnimplementedCloudUserCenterServer) UserInfoGet(context.Context, *UserInfoGetRequest) (*UserInfoGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserInfoGet not implemented")
}
func (UnimplementedCloudUserCenterServer) MUserInfoGet(context.Context, *MUserInfoGetRequest) (*MUserInfoGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MUserInfoGet not implemented")
}
func (UnimplementedCloudUserCenterServer) UserInfoGetByName(context.Context, *UserInfoGetByNameRequest) (*UserInfoGetByNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserInfoGetByName not implemented")
}
func (UnimplementedCloudUserCenterServer) UserInfoSearch(context.Context, *UserInfoSearchRequest) (*UserInfoSearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserInfoSearch not implemented")
}
func (UnimplementedCloudUserCenterServer) UserMessageCreate(context.Context, *UserMessageCreateRequest) (*UserMessageCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserMessageCreate not implemented")
}
func (UnimplementedCloudUserCenterServer) MUserMessageCreate(context.Context, *MUserMessageCreateRequest) (*MUserMessageCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MUserMessageCreate not implemented")
}
func (UnimplementedCloudUserCenterServer) UserMessageList(context.Context, *UserMessageListRequest) (*UserMessageListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserMessageList not implemented")
}
func (UnimplementedCloudUserCenterServer) UserMessageGet(context.Context, *UserMessageGetRequest) (*UserMessageGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserMessageGet not implemented")
}
func (UnimplementedCloudUserCenterServer) UserMessageUpdate(context.Context, *UserMessageUpdateRequest) (*UserMessageUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserMessageUpdate not implemented")
}
func (UnimplementedCloudUserCenterServer) UserMessageDelete(context.Context, *UserMessageDeleteRequest) (*UserMessageDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserMessageDelete not implemented")
}
func (UnimplementedCloudUserCenterServer) mustEmbedUnimplementedCloudUserCenterServer() {}

// UnsafeCloudUserCenterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CloudUserCenterServer will
// result in compilation errors.
type UnsafeCloudUserCenterServer interface {
	mustEmbedUnimplementedCloudUserCenterServer()
}

func RegisterCloudUserCenterServer(s grpc.ServiceRegistrar, srv CloudUserCenterServer) {
	s.RegisterService(&CloudUserCenter_ServiceDesc, srv)
}

func _CloudUserCenter_UserInfoCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudUserCenterServer).UserInfoCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud_user_center.CloudUserCenter/UserInfoCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudUserCenterServer).UserInfoCreate(ctx, req.(*UserInfoCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudUserCenter_UserInfoAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudUserCenterServer).UserInfoAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud_user_center.CloudUserCenter/UserInfoAuth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudUserCenterServer).UserInfoAuth(ctx, req.(*UserInfoAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudUserCenter_UserInfoUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudUserCenterServer).UserInfoUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud_user_center.CloudUserCenter/UserInfoUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudUserCenterServer).UserInfoUpdate(ctx, req.(*UserInfoUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudUserCenter_UserInfoDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudUserCenterServer).UserInfoDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud_user_center.CloudUserCenter/UserInfoDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudUserCenterServer).UserInfoDelete(ctx, req.(*UserInfoDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudUserCenter_UserInfoGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudUserCenterServer).UserInfoGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud_user_center.CloudUserCenter/UserInfoGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudUserCenterServer).UserInfoGet(ctx, req.(*UserInfoGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudUserCenter_MUserInfoGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MUserInfoGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudUserCenterServer).MUserInfoGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud_user_center.CloudUserCenter/MUserInfoGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudUserCenterServer).MUserInfoGet(ctx, req.(*MUserInfoGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudUserCenter_UserInfoGetByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoGetByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudUserCenterServer).UserInfoGetByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud_user_center.CloudUserCenter/UserInfoGetByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudUserCenterServer).UserInfoGetByName(ctx, req.(*UserInfoGetByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudUserCenter_UserInfoSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudUserCenterServer).UserInfoSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud_user_center.CloudUserCenter/UserInfoSearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudUserCenterServer).UserInfoSearch(ctx, req.(*UserInfoSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudUserCenter_UserMessageCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserMessageCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudUserCenterServer).UserMessageCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud_user_center.CloudUserCenter/UserMessageCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudUserCenterServer).UserMessageCreate(ctx, req.(*UserMessageCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudUserCenter_MUserMessageCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MUserMessageCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudUserCenterServer).MUserMessageCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud_user_center.CloudUserCenter/MUserMessageCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudUserCenterServer).MUserMessageCreate(ctx, req.(*MUserMessageCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudUserCenter_UserMessageList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserMessageListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudUserCenterServer).UserMessageList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud_user_center.CloudUserCenter/UserMessageList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudUserCenterServer).UserMessageList(ctx, req.(*UserMessageListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudUserCenter_UserMessageGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserMessageGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudUserCenterServer).UserMessageGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud_user_center.CloudUserCenter/UserMessageGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudUserCenterServer).UserMessageGet(ctx, req.(*UserMessageGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudUserCenter_UserMessageUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserMessageUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudUserCenterServer).UserMessageUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud_user_center.CloudUserCenter/UserMessageUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudUserCenterServer).UserMessageUpdate(ctx, req.(*UserMessageUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudUserCenter_UserMessageDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserMessageDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudUserCenterServer).UserMessageDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud_user_center.CloudUserCenter/UserMessageDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudUserCenterServer).UserMessageDelete(ctx, req.(*UserMessageDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CloudUserCenter_ServiceDesc is the grpc.ServiceDesc for CloudUserCenter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CloudUserCenter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloud_user_center.CloudUserCenter",
	HandlerType: (*CloudUserCenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserInfoCreate",
			Handler:    _CloudUserCenter_UserInfoCreate_Handler,
		},
		{
			MethodName: "UserInfoAuth",
			Handler:    _CloudUserCenter_UserInfoAuth_Handler,
		},
		{
			MethodName: "UserInfoUpdate",
			Handler:    _CloudUserCenter_UserInfoUpdate_Handler,
		},
		{
			MethodName: "UserInfoDelete",
			Handler:    _CloudUserCenter_UserInfoDelete_Handler,
		},
		{
			MethodName: "UserInfoGet",
			Handler:    _CloudUserCenter_UserInfoGet_Handler,
		},
		{
			MethodName: "MUserInfoGet",
			Handler:    _CloudUserCenter_MUserInfoGet_Handler,
		},
		{
			MethodName: "UserInfoGetByName",
			Handler:    _CloudUserCenter_UserInfoGetByName_Handler,
		},
		{
			MethodName: "UserInfoSearch",
			Handler:    _CloudUserCenter_UserInfoSearch_Handler,
		},
		{
			MethodName: "UserMessageCreate",
			Handler:    _CloudUserCenter_UserMessageCreate_Handler,
		},
		{
			MethodName: "MUserMessageCreate",
			Handler:    _CloudUserCenter_MUserMessageCreate_Handler,
		},
		{
			MethodName: "UserMessageList",
			Handler:    _CloudUserCenter_UserMessageList_Handler,
		},
		{
			MethodName: "UserMessageGet",
			Handler:    _CloudUserCenter_UserMessageGet_Handler,
		},
		{
			MethodName: "UserMessageUpdate",
			Handler:    _CloudUserCenter_UserMessageUpdate_Handler,
		},
		{
			MethodName: "UserMessageDelete",
			Handler:    _CloudUserCenter_UserMessageDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
