// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.1
// source: model_api.proto

package model_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_model_api_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HelloReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_model_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_model_api_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ModelCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId        int64         `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                         // 用户id
	ModelName     string        `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`                                 // 模型名称
	ModelCategory ModelCategory `protobuf:"varint,3,opt,name=model_category,json=modelCategory,proto3,enum=ModelCategory" json:"model_category,omitempty"` // 模型类别
	ModelType     ModelType     `protobuf:"varint,4,opt,name=model_type,json=modelType,proto3,enum=ModelType" json:"model_type,omitempty"`                 // 模型类型
}

func (x *ModelCreateRequest) Reset() {
	*x = ModelCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelCreateRequest) ProtoMessage() {}

func (x *ModelCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelCreateRequest.ProtoReflect.Descriptor instead.
func (*ModelCreateRequest) Descriptor() ([]byte, []int) {
	return file_model_api_proto_rawDescGZIP(), []int{2}
}

func (x *ModelCreateRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ModelCreateRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *ModelCreateRequest) GetModelCategory() ModelCategory {
	if x != nil {
		return x.ModelCategory
	}
	return ModelCategory_model_category_unknown
}

func (x *ModelCreateRequest) GetModelType() ModelType {
	if x != nil {
		return x.ModelType
	}
	return ModelType_model_type_unknown
}

type ModelCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int32                     `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Msg        string                    `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data       *ModelCreateResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ModelCreateResponse) Reset() {
	*x = ModelCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelCreateResponse) ProtoMessage() {}

func (x *ModelCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelCreateResponse.ProtoReflect.Descriptor instead.
func (*ModelCreateResponse) Descriptor() ([]byte, []int) {
	return file_model_api_proto_rawDescGZIP(), []int{3}
}

func (x *ModelCreateResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ModelCreateResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ModelCreateResponse) GetData() *ModelCreateResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// 用户选择预训练的场景下，则忽略num_classes, fix_resize_size 以及image_data_size属性
type ModelTrainRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId            int64                `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ModelId           int64                `protobuf:"varint,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`                                  // 模型id
	TrainDatasetId    int64                `protobuf:"varint,3,opt,name=train_dataset_id,json=trainDatasetId,proto3" json:"train_dataset_id,omitempty"`           // 训练数据集id
	ValDatasetId      int64                `protobuf:"varint,4,opt,name=val_dataset_id,json=valDatasetId,proto3" json:"val_dataset_id,omitempty"`                 // 验证数据集id
	TrainDatasetRatio float64              `protobuf:"fixed64,5,opt,name=train_dataset_ratio,json=trainDatasetRatio,proto3" json:"train_dataset_ratio,omitempty"` // 训练集占比, 只有当用户不指定验证集(val_dataset)时才会使用这个数据
	ImageSize         *ImageDataSize       `protobuf:"bytes,6,opt,name=image_size,json=imageSize,proto3" json:"image_size,omitempty"`                             // 图像尺寸
	IterationParam    *TrainIterationParam `protobuf:"bytes,12,opt,name=iteration_param,json=iterationParam,proto3" json:"iteration_param,omitempty"`             // 迭代参数
	DataAugmentation  *DataAugmentation    `protobuf:"bytes,13,opt,name=data_augmentation,json=dataAugmentation,proto3" json:"data_augmentation,omitempty"`       // 数据增项选项
	DataRichCrop      *DataRichCrop        `protobuf:"bytes,14,opt,name=data_rich_crop,json=dataRichCrop,proto3" json:"data_rich_crop,omitempty"`                 // 数据增广选项
	PretrainedModelId int64                `protobuf:"varint,16,opt,name=pretrained_model_id,json=pretrainedModelId,proto3" json:"pretrained_model_id,omitempty"` // 预训练模型id, 模型必须属于已经训练完成的状态才能选择
}

func (x *ModelTrainRequest) Reset() {
	*x = ModelTrainRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelTrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelTrainRequest) ProtoMessage() {}

func (x *ModelTrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelTrainRequest.ProtoReflect.Descriptor instead.
func (*ModelTrainRequest) Descriptor() ([]byte, []int) {
	return file_model_api_proto_rawDescGZIP(), []int{4}
}

func (x *ModelTrainRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ModelTrainRequest) GetModelId() int64 {
	if x != nil {
		return x.ModelId
	}
	return 0
}

func (x *ModelTrainRequest) GetTrainDatasetId() int64 {
	if x != nil {
		return x.TrainDatasetId
	}
	return 0
}

func (x *ModelTrainRequest) GetValDatasetId() int64 {
	if x != nil {
		return x.ValDatasetId
	}
	return 0
}

func (x *ModelTrainRequest) GetTrainDatasetRatio() float64 {
	if x != nil {
		return x.TrainDatasetRatio
	}
	return 0
}

func (x *ModelTrainRequest) GetImageSize() *ImageDataSize {
	if x != nil {
		return x.ImageSize
	}
	return nil
}

func (x *ModelTrainRequest) GetIterationParam() *TrainIterationParam {
	if x != nil {
		return x.IterationParam
	}
	return nil
}

func (x *ModelTrainRequest) GetDataAugmentation() *DataAugmentation {
	if x != nil {
		return x.DataAugmentation
	}
	return nil
}

func (x *ModelTrainRequest) GetDataRichCrop() *DataRichCrop {
	if x != nil {
		return x.DataRichCrop
	}
	return nil
}

func (x *ModelTrainRequest) GetPretrainedModelId() int64 {
	if x != nil {
		return x.PretrainedModelId
	}
	return 0
}

type ModelTrainResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int32                    `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Msg        string                   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data       *ModelTrainResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ModelTrainResponse) Reset() {
	*x = ModelTrainResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelTrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelTrainResponse) ProtoMessage() {}

func (x *ModelTrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelTrainResponse.ProtoReflect.Descriptor instead.
func (*ModelTrainResponse) Descriptor() ([]byte, []int) {
	return file_model_api_proto_rawDescGZIP(), []int{5}
}

func (x *ModelTrainResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ModelTrainResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ModelTrainResponse) GetData() *ModelTrainResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// 模型预测 path: /model_predict
type ModelPredictRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId             int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                        // 用户id
	ModelId            int64    `protobuf:"varint,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`                                     // 模型名称
	PredictFileUrlList []string `protobuf:"bytes,3,rep,name=predict_file_url_list,json=predictFileUrlList,proto3" json:"predict_file_url_list,omitempty"` // 待预测图像的url列表, 可以是dicom文件
	IsDicom            bool     `protobuf:"varint,4,opt,name=is_dicom,json=isDicom,proto3" json:"is_dicom,omitempty"`                                     // 是否为dicom文件
}

func (x *ModelPredictRequest) Reset() {
	*x = ModelPredictRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelPredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelPredictRequest) ProtoMessage() {}

func (x *ModelPredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelPredictRequest.ProtoReflect.Descriptor instead.
func (*ModelPredictRequest) Descriptor() ([]byte, []int) {
	return file_model_api_proto_rawDescGZIP(), []int{6}
}

func (x *ModelPredictRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ModelPredictRequest) GetModelId() int64 {
	if x != nil {
		return x.ModelId
	}
	return 0
}

func (x *ModelPredictRequest) GetPredictFileUrlList() []string {
	if x != nil {
		return x.PredictFileUrlList
	}
	return nil
}

func (x *ModelPredictRequest) GetIsDicom() bool {
	if x != nil {
		return x.IsDicom
	}
	return false
}

type OutlinePoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Points []int32 `protobuf:"varint,1,rep,packed,name=points,proto3" json:"points,omitempty"`
}

func (x *OutlinePoint) Reset() {
	*x = OutlinePoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutlinePoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutlinePoint) ProtoMessage() {}

func (x *OutlinePoint) ProtoReflect() protoreflect.Message {
	mi := &file_model_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutlinePoint.ProtoReflect.Descriptor instead.
func (*OutlinePoint) Descriptor() ([]byte, []int) {
	return file_model_api_proto_rawDescGZIP(), []int{7}
}

func (x *OutlinePoint) GetPoints() []int32 {
	if x != nil {
		return x.Points
	}
	return nil
}

// slice上的轮廓
type SliceOutLine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PointMap map[int32]*OutlinePoint `protobuf:"bytes,2,rep,name=point_map,json=pointMap,proto3" json:"point_map,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *SliceOutLine) Reset() {
	*x = SliceOutLine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SliceOutLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SliceOutLine) ProtoMessage() {}

func (x *SliceOutLine) ProtoReflect() protoreflect.Message {
	mi := &file_model_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SliceOutLine.ProtoReflect.Descriptor instead.
func (*SliceOutLine) Descriptor() ([]byte, []int) {
	return file_model_api_proto_rawDescGZIP(), []int{8}
}

func (x *SliceOutLine) GetPointMap() map[int32]*OutlinePoint {
	if x != nil {
		return x.PointMap
	}
	return nil
}

type ModelPredictResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int32                      `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Msg        string                     `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data       *ModelPredictResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ModelPredictResponse) Reset() {
	*x = ModelPredictResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelPredictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelPredictResponse) ProtoMessage() {}

func (x *ModelPredictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelPredictResponse.ProtoReflect.Descriptor instead.
func (*ModelPredictResponse) Descriptor() ([]byte, []int) {
	return file_model_api_proto_rawDescGZIP(), []int{9}
}

func (x *ModelPredictResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ModelPredictResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ModelPredictResponse) GetData() *ModelPredictResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// 模型列表
type ModelListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   int64        `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户id
	Page     int32        `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int32        `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SortType DataSortType `protobuf:"varint,4,opt,name=sort_type,json=sortType,proto3,enum=DataSortType" json:"sort_type,omitempty"` // 排序规则
}

func (x *ModelListRequest) Reset() {
	*x = ModelListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelListRequest) ProtoMessage() {}

func (x *ModelListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelListRequest.ProtoReflect.Descriptor instead.
func (*ModelListRequest) Descriptor() ([]byte, []int) {
	return file_model_api_proto_rawDescGZIP(), []int{10}
}

func (x *ModelListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ModelListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ModelListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ModelListRequest) GetSortType() DataSortType {
	if x != nil {
		return x.SortType
	}
	return DataSortType_sort_type_unknown
}

type ModelListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int32                   `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Msg        string                  `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data       *ModelListResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ModelListResponse) Reset() {
	*x = ModelListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelListResponse) ProtoMessage() {}

func (x *ModelListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelListResponse.ProtoReflect.Descriptor instead.
func (*ModelListResponse) Descriptor() ([]byte, []int) {
	return file_model_api_proto_rawDescGZIP(), []int{11}
}

func (x *ModelListResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ModelListResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ModelListResponse) GetData() *ModelListResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// 模型搜索
type ModelSearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   int64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Keywords string `protobuf:"bytes,2,opt,name=keywords,proto3" json:"keywords,omitempty"` // 关键词
	Page     int32  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int32  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *ModelSearchRequest) Reset() {
	*x = ModelSearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelSearchRequest) ProtoMessage() {}

func (x *ModelSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelSearchRequest.ProtoReflect.Descriptor instead.
func (*ModelSearchRequest) Descriptor() ([]byte, []int) {
	return file_model_api_proto_rawDescGZIP(), []int{12}
}

func (x *ModelSearchRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ModelSearchRequest) GetKeywords() string {
	if x != nil {
		return x.Keywords
	}
	return ""
}

func (x *ModelSearchRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ModelSearchRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ModelSearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int32                     `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Msg        string                    `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data       *ModelSearchResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ModelSearchResponse) Reset() {
	*x = ModelSearchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_api_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelSearchResponse) ProtoMessage() {}

func (x *ModelSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_api_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelSearchResponse.ProtoReflect.Descriptor instead.
func (*ModelSearchResponse) Descriptor() ([]byte, []int) {
	return file_model_api_proto_rawDescGZIP(), []int{13}
}

func (x *ModelSearchResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ModelSearchResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ModelSearchResponse) GetData() *ModelSearchResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// 模型详情
type ModelGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`    // 用户id
	ModelId int64 `protobuf:"varint,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"` // 模型id
}

func (x *ModelGetRequest) Reset() {
	*x = ModelGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_api_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelGetRequest) ProtoMessage() {}

func (x *ModelGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_api_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelGetRequest.ProtoReflect.Descriptor instead.
func (*ModelGetRequest) Descriptor() ([]byte, []int) {
	return file_model_api_proto_rawDescGZIP(), []int{14}
}

func (x *ModelGetRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ModelGetRequest) GetModelId() int64 {
	if x != nil {
		return x.ModelId
	}
	return 0
}

type ModelGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Msg        string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data       *ModelGetResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ModelGetResponse) Reset() {
	*x = ModelGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_api_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelGetResponse) ProtoMessage() {}

func (x *ModelGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_api_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelGetResponse.ProtoReflect.Descriptor instead.
func (*ModelGetResponse) Descriptor() ([]byte, []int) {
	return file_model_api_proto_rawDescGZIP(), []int{15}
}

func (x *ModelGetResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ModelGetResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ModelGetResponse) GetData() *ModelGetResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// 删除模型
type ModelDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`    // 用户id
	ModelId int64 `protobuf:"varint,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"` // 模型id
}

func (x *ModelDeleteRequest) Reset() {
	*x = ModelDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_api_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelDeleteRequest) ProtoMessage() {}

func (x *ModelDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_api_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelDeleteRequest.ProtoReflect.Descriptor instead.
func (*ModelDeleteRequest) Descriptor() ([]byte, []int) {
	return file_model_api_proto_rawDescGZIP(), []int{16}
}

func (x *ModelDeleteRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ModelDeleteRequest) GetModelId() int64 {
	if x != nil {
		return x.ModelId
	}
	return 0
}

type ModelDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int32                     `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Msg        string                    `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data       *ModelDeleteResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ModelDeleteResponse) Reset() {
	*x = ModelDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_api_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelDeleteResponse) ProtoMessage() {}

func (x *ModelDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_api_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelDeleteResponse.ProtoReflect.Descriptor instead.
func (*ModelDeleteResponse) Descriptor() ([]byte, []int) {
	return file_model_api_proto_rawDescGZIP(), []int{17}
}

func (x *ModelDeleteResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ModelDeleteResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ModelDeleteResponse) GetData() *ModelDeleteResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// 分享模型
type ModelShareRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId        int64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                       // 用户id
	ShareUserName string `protobuf:"bytes,2,opt,name=share_user_name,json=shareUserName,proto3" json:"share_user_name,omitempty"` // 分享人姓名
	ModelId       int64  `protobuf:"varint,3,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`                    // 模型id
	CanShare      int32  `protobuf:"varint,4,opt,name=can_share,json=canShare,proto3" json:"can_share,omitempty"`                 // 是否可以二次分享
	CanEdit       int32  `protobuf:"varint,5,opt,name=can_edit,json=canEdit,proto3" json:"can_edit,omitempty"`                    // 是否可以二次编辑
}

func (x *ModelShareRequest) Reset() {
	*x = ModelShareRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_api_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelShareRequest) ProtoMessage() {}

func (x *ModelShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_api_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelShareRequest.ProtoReflect.Descriptor instead.
func (*ModelShareRequest) Descriptor() ([]byte, []int) {
	return file_model_api_proto_rawDescGZIP(), []int{18}
}

func (x *ModelShareRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ModelShareRequest) GetShareUserName() string {
	if x != nil {
		return x.ShareUserName
	}
	return ""
}

func (x *ModelShareRequest) GetModelId() int64 {
	if x != nil {
		return x.ModelId
	}
	return 0
}

func (x *ModelShareRequest) GetCanShare() int32 {
	if x != nil {
		return x.CanShare
	}
	return 0
}

func (x *ModelShareRequest) GetCanEdit() int32 {
	if x != nil {
		return x.CanEdit
	}
	return 0
}

type ModelShareResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int32                    `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Msg        string                   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data       *ModelShareResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ModelShareResponse) Reset() {
	*x = ModelShareResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_api_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelShareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelShareResponse) ProtoMessage() {}

func (x *ModelShareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_api_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelShareResponse.ProtoReflect.Descriptor instead.
func (*ModelShareResponse) Descriptor() ([]byte, []int) {
	return file_model_api_proto_rawDescGZIP(), []int{19}
}

func (x *ModelShareResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ModelShareResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ModelShareResponse) GetData() *ModelShareResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type ModelCreateResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModelId int64 `protobuf:"varint,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"` // 模型id
}

func (x *ModelCreateResponse_Data) Reset() {
	*x = ModelCreateResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_api_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelCreateResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelCreateResponse_Data) ProtoMessage() {}

func (x *ModelCreateResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_model_api_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelCreateResponse_Data.ProtoReflect.Descriptor instead.
func (*ModelCreateResponse_Data) Descriptor() ([]byte, []int) {
	return file_model_api_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ModelCreateResponse_Data) GetModelId() int64 {
	if x != nil {
		return x.ModelId
	}
	return 0
}

type ModelTrainResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModelId          int64  `protobuf:"varint,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`      // 模型id
	ModelName        string `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"` // 模型名称
	ModelTrainTaskId string `protobuf:"bytes,3,opt,name=ModelTrainTaskId,proto3" json:"ModelTrainTaskId,omitempty"`    // 模型训练任务id
}

func (x *ModelTrainResponse_Data) Reset() {
	*x = ModelTrainResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_api_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelTrainResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelTrainResponse_Data) ProtoMessage() {}

func (x *ModelTrainResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_model_api_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelTrainResponse_Data.ProtoReflect.Descriptor instead.
func (*ModelTrainResponse_Data) Descriptor() ([]byte, []int) {
	return file_model_api_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ModelTrainResponse_Data) GetModelId() int64 {
	if x != nil {
		return x.ModelId
	}
	return 0
}

func (x *ModelTrainResponse_Data) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *ModelTrainResponse_Data) GetModelTrainTaskId() string {
	if x != nil {
		return x.ModelTrainTaskId
	}
	return ""
}

type ModelPredictResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResultImageList []string                `protobuf:"bytes,1,rep,name=result_image_list,json=resultImageList,proto3" json:"result_image_list,omitempty"`                                               // 结果的url列表
	Result          map[int32]*SliceOutLine `protobuf:"bytes,2,rep,name=result,proto3" json:"result,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 轮廓点
}

func (x *ModelPredictResponse_Data) Reset() {
	*x = ModelPredictResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_api_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelPredictResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelPredictResponse_Data) ProtoMessage() {}

func (x *ModelPredictResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_model_api_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelPredictResponse_Data.ProtoReflect.Descriptor instead.
func (*ModelPredictResponse_Data) Descriptor() ([]byte, []int) {
	return file_model_api_proto_rawDescGZIP(), []int{9, 0}
}

func (x *ModelPredictResponse_Data) GetResultImageList() []string {
	if x != nil {
		return x.ResultImageList
	}
	return nil
}

func (x *ModelPredictResponse_Data) GetResult() map[int32]*SliceOutLine {
	if x != nil {
		return x.Result
	}
	return nil
}

type ModelListResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Models []*UserModel `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"` // 模型列表
	Total  int32        `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`  // 总数
}

func (x *ModelListResponse_Data) Reset() {
	*x = ModelListResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_api_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelListResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelListResponse_Data) ProtoMessage() {}

func (x *ModelListResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_model_api_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelListResponse_Data.ProtoReflect.Descriptor instead.
func (*ModelListResponse_Data) Descriptor() ([]byte, []int) {
	return file_model_api_proto_rawDescGZIP(), []int{11, 0}
}

func (x *ModelListResponse_Data) GetModels() []*UserModel {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *ModelListResponse_Data) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ModelSearchResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Models []*UserModel `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"` // 模型列表
	Total  int32        `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`  // 总数
}

func (x *ModelSearchResponse_Data) Reset() {
	*x = ModelSearchResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_api_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelSearchResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelSearchResponse_Data) ProtoMessage() {}

func (x *ModelSearchResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_model_api_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelSearchResponse_Data.ProtoReflect.Descriptor instead.
func (*ModelSearchResponse_Data) Descriptor() ([]byte, []int) {
	return file_model_api_proto_rawDescGZIP(), []int{13, 0}
}

func (x *ModelSearchResponse_Data) GetModels() []*UserModel {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *ModelSearchResponse_Data) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ModelGetResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model *UserModel `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"` // 模型
}

func (x *ModelGetResponse_Data) Reset() {
	*x = ModelGetResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_api_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelGetResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelGetResponse_Data) ProtoMessage() {}

func (x *ModelGetResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_model_api_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelGetResponse_Data.ProtoReflect.Descriptor instead.
func (*ModelGetResponse_Data) Descriptor() ([]byte, []int) {
	return file_model_api_proto_rawDescGZIP(), []int{15, 0}
}

func (x *ModelGetResponse_Data) GetModel() *UserModel {
	if x != nil {
		return x.Model
	}
	return nil
}

type ModelDeleteResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ModelDeleteResponse_Data) Reset() {
	*x = ModelDeleteResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_api_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelDeleteResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelDeleteResponse_Data) ProtoMessage() {}

func (x *ModelDeleteResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_model_api_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelDeleteResponse_Data.ProtoReflect.Descriptor instead.
func (*ModelDeleteResponse_Data) Descriptor() ([]byte, []int) {
	return file_model_api_proto_rawDescGZIP(), []int{17, 0}
}

type ModelShareResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ModelShareResponse_Data) Reset() {
	*x = ModelShareResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_api_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelShareResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelShareResponse_Data) ProtoMessage() {}

func (x *ModelShareResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_model_api_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelShareResponse_Data.ProtoReflect.Descriptor instead.
func (*ModelShareResponse_Data) Descriptor() ([]byte, []int) {
	return file_model_api_proto_rawDescGZIP(), []int{19, 0}
}

var File_model_api_proto protoreflect.FileDescriptor

var file_model_api_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x61, 0x70, 0x69, 0x1a, 0x10, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x22,
	0x0a, 0x0c, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x26, 0x0a, 0x0a, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xae, 0x01, 0x0a, 0x12, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x35, 0x0a, 0x0e, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0e, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x52, 0x0d, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x12, 0x29, 0x0a, 0x0a, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x22, 0xa4, 0x01, 0x0a, 0x13,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x37, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a,
	0x21, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x49, 0x64, 0x22, 0xda, 0x03, 0x0a, 0x11, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x54, 0x72, 0x61, 0x69,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x10,
	0x74, 0x72, 0x61, 0x69, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x44, 0x61, 0x74,
	0x61, 0x73, 0x65, 0x74, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x76, 0x61, 0x6c, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c,
	0x76, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x13,
	0x74, 0x72, 0x61, 0x69, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x5f, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x11, 0x74, 0x72, 0x61, 0x69, 0x6e,
	0x44, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x52, 0x61, 0x74, 0x69, 0x6f, 0x12, 0x2d, 0x0a, 0x0a,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x53, 0x69, 0x7a, 0x65,
	0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x3d, 0x0a, 0x0f, 0x69,
	0x74, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x49, 0x74, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x0e, 0x69, 0x74, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x3e, 0x0a, 0x11, 0x64, 0x61,
	0x74, 0x61, 0x5f, 0x61, 0x75, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x41, 0x75, 0x67, 0x6d,
	0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x10, 0x64, 0x61, 0x74, 0x61, 0x41, 0x75,
	0x67, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x33, 0x0a, 0x0e, 0x64, 0x61,
	0x74, 0x61, 0x5f, 0x72, 0x69, 0x63, 0x68, 0x5f, 0x63, 0x72, 0x6f, 0x70, 0x18, 0x0e, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x69, 0x63, 0x68, 0x43, 0x72, 0x6f,
	0x70, 0x52, 0x0c, 0x64, 0x61, 0x74, 0x61, 0x52, 0x69, 0x63, 0x68, 0x43, 0x72, 0x6f, 0x70, 0x12,
	0x2e, 0x0a, 0x13, 0x70, 0x72, 0x65, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x65, 0x64, 0x5f, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x10, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x70, 0x72,
	0x65, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x65, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x49, 0x64, 0x22,
	0xed, 0x01, 0x0a, 0x12, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x36, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f,
	0x61, 0x70, 0x69, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x1a, 0x6c, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x54, 0x72, 0x61, 0x69,
	0x6e, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x22,
	0x97, 0x01, 0x0a, 0x13, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x19, 0x0a, 0x08, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x31, 0x0a, 0x15, 0x70,
	0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x5f,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x12, 0x70, 0x72, 0x65, 0x64,
	0x69, 0x63, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x72, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x19,
	0x0a, 0x08, 0x69, 0x73, 0x5f, 0x64, 0x69, 0x63, 0x6f, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x69, 0x73, 0x44, 0x69, 0x63, 0x6f, 0x6d, 0x22, 0x26, 0x0a, 0x0c, 0x4f, 0x75, 0x74,
	0x6c, 0x69, 0x6e, 0x65, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x73, 0x22, 0xa8, 0x01, 0x0a, 0x0c, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x4f, 0x75, 0x74, 0x4c, 0x69,
	0x6e, 0x65, 0x12, 0x42, 0x0a, 0x09, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x6d, 0x61, 0x70, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x61, 0x70,
	0x69, 0x2e, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x4f, 0x75, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x2e, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x4d, 0x61, 0x70, 0x1a, 0x54, 0x0a, 0x0d, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x4d,
	0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2d, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x4f, 0x75, 0x74, 0x6c, 0x69, 0x6e, 0x65, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xd6, 0x02, 0x0a,
	0x14, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x38, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x61,
	0x70, 0x69, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x1a, 0xd0, 0x01, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2a, 0x0a, 0x11, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x48, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f,
	0x61, 0x70, 0x69, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x1a, 0x52, 0x0a, 0x0b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x2d, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x6c,
	0x69, 0x63, 0x65, 0x4f, 0x75, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x88, 0x01, 0x0a, 0x10, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x2a, 0x0a, 0x09, 0x73, 0x6f, 0x72, 0x74, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f,
	0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x73, 0x6f, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x22, 0xbf, 0x01, 0x0a, 0x11, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x35, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f,
	0x61, 0x70, 0x69, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x1a, 0x40, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x22, 0x0a, 0x06, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x52, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x22, 0x7a, 0x0a, 0x12, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0xc3,
	0x01, 0x0a, 0x13, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x37, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f,
	0x61, 0x70, 0x69, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x1a, 0x40, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x22, 0x0a, 0x06, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x22, 0x45, 0x0a, 0x0f, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x19, 0x0a, 0x08, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x49, 0x64, 0x22, 0xa5, 0x01, 0x0a, 0x10,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x12, 0x34, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x28, 0x0a, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x20, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x05, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x22, 0x48, 0x0a, 0x12, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x49, 0x64, 0x22, 0x89, 0x01,
	0x0a, 0x13, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x37, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x61,
	0x70, 0x69, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x1a, 0x06, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0xa7, 0x01, 0x0a, 0x11, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x53, 0x68, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x73, 0x68, 0x61, 0x72,
	0x65, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x73, 0x68, 0x61, 0x72, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x19, 0x0a, 0x08, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63,
	0x61, 0x6e, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x63, 0x61, 0x6e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x61, 0x6e, 0x5f,
	0x65, 0x64, 0x69, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x61, 0x6e, 0x45,
	0x64, 0x69, 0x74, 0x22, 0x87, 0x01, 0x0a, 0x12, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x68, 0x61,
	0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x36, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x68, 0x61,
	0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x06, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x42, 0x1f, 0x5a,
	0x1d, 0x2e, 0x2e, 0x2f, 0x2e, 0x2e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x70,
	0x62, 0x67, 0x65, 0x6e, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x61, 0x70, 0x69, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_model_api_proto_rawDescOnce sync.Once
	file_model_api_proto_rawDescData = file_model_api_proto_rawDesc
)

func file_model_api_proto_rawDescGZIP() []byte {
	file_model_api_proto_rawDescOnce.Do(func() {
		file_model_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_model_api_proto_rawDescData)
	})
	return file_model_api_proto_rawDescData
}

var file_model_api_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_model_api_proto_goTypes = []interface{}{
	(*HelloRequest)(nil),              // 0: model_api.HelloRequest
	(*HelloReply)(nil),                // 1: model_api.HelloReply
	(*ModelCreateRequest)(nil),        // 2: model_api.ModelCreateRequest
	(*ModelCreateResponse)(nil),       // 3: model_api.ModelCreateResponse
	(*ModelTrainRequest)(nil),         // 4: model_api.ModelTrainRequest
	(*ModelTrainResponse)(nil),        // 5: model_api.ModelTrainResponse
	(*ModelPredictRequest)(nil),       // 6: model_api.ModelPredictRequest
	(*OutlinePoint)(nil),              // 7: model_api.OutlinePoint
	(*SliceOutLine)(nil),              // 8: model_api.SliceOutLine
	(*ModelPredictResponse)(nil),      // 9: model_api.ModelPredictResponse
	(*ModelListRequest)(nil),          // 10: model_api.ModelListRequest
	(*ModelListResponse)(nil),         // 11: model_api.ModelListResponse
	(*ModelSearchRequest)(nil),        // 12: model_api.ModelSearchRequest
	(*ModelSearchResponse)(nil),       // 13: model_api.ModelSearchResponse
	(*ModelGetRequest)(nil),           // 14: model_api.ModelGetRequest
	(*ModelGetResponse)(nil),          // 15: model_api.ModelGetResponse
	(*ModelDeleteRequest)(nil),        // 16: model_api.ModelDeleteRequest
	(*ModelDeleteResponse)(nil),       // 17: model_api.ModelDeleteResponse
	(*ModelShareRequest)(nil),         // 18: model_api.ModelShareRequest
	(*ModelShareResponse)(nil),        // 19: model_api.ModelShareResponse
	(*ModelCreateResponse_Data)(nil),  // 20: model_api.ModelCreateResponse.Data
	(*ModelTrainResponse_Data)(nil),   // 21: model_api.ModelTrainResponse.Data
	nil,                               // 22: model_api.SliceOutLine.PointMapEntry
	(*ModelPredictResponse_Data)(nil), // 23: model_api.ModelPredictResponse.Data
	nil,                               // 24: model_api.ModelPredictResponse.Data.ResultEntry
	(*ModelListResponse_Data)(nil),    // 25: model_api.ModelListResponse.Data
	(*ModelSearchResponse_Data)(nil),  // 26: model_api.ModelSearchResponse.Data
	(*ModelGetResponse_Data)(nil),     // 27: model_api.ModelGetResponse.Data
	(*ModelDeleteResponse_Data)(nil),  // 28: model_api.ModelDeleteResponse.Data
	(*ModelShareResponse_Data)(nil),   // 29: model_api.ModelShareResponse.Data
	(ModelCategory)(0),                // 30: ModelCategory
	(ModelType)(0),                    // 31: ModelType
	(*ImageDataSize)(nil),             // 32: ImageDataSize
	(*TrainIterationParam)(nil),       // 33: TrainIterationParam
	(*DataAugmentation)(nil),          // 34: DataAugmentation
	(*DataRichCrop)(nil),              // 35: DataRichCrop
	(DataSortType)(0),                 // 36: DataSortType
	(*UserModel)(nil),                 // 37: UserModel
}
var file_model_api_proto_depIdxs = []int32{
	30, // 0: model_api.ModelCreateRequest.model_category:type_name -> ModelCategory
	31, // 1: model_api.ModelCreateRequest.model_type:type_name -> ModelType
	20, // 2: model_api.ModelCreateResponse.data:type_name -> model_api.ModelCreateResponse.Data
	32, // 3: model_api.ModelTrainRequest.image_size:type_name -> ImageDataSize
	33, // 4: model_api.ModelTrainRequest.iteration_param:type_name -> TrainIterationParam
	34, // 5: model_api.ModelTrainRequest.data_augmentation:type_name -> DataAugmentation
	35, // 6: model_api.ModelTrainRequest.data_rich_crop:type_name -> DataRichCrop
	21, // 7: model_api.ModelTrainResponse.data:type_name -> model_api.ModelTrainResponse.Data
	22, // 8: model_api.SliceOutLine.point_map:type_name -> model_api.SliceOutLine.PointMapEntry
	23, // 9: model_api.ModelPredictResponse.data:type_name -> model_api.ModelPredictResponse.Data
	36, // 10: model_api.ModelListRequest.sort_type:type_name -> DataSortType
	25, // 11: model_api.ModelListResponse.data:type_name -> model_api.ModelListResponse.Data
	26, // 12: model_api.ModelSearchResponse.data:type_name -> model_api.ModelSearchResponse.Data
	27, // 13: model_api.ModelGetResponse.data:type_name -> model_api.ModelGetResponse.Data
	28, // 14: model_api.ModelDeleteResponse.data:type_name -> model_api.ModelDeleteResponse.Data
	29, // 15: model_api.ModelShareResponse.data:type_name -> model_api.ModelShareResponse.Data
	7,  // 16: model_api.SliceOutLine.PointMapEntry.value:type_name -> model_api.OutlinePoint
	24, // 17: model_api.ModelPredictResponse.Data.result:type_name -> model_api.ModelPredictResponse.Data.ResultEntry
	8,  // 18: model_api.ModelPredictResponse.Data.ResultEntry.value:type_name -> model_api.SliceOutLine
	37, // 19: model_api.ModelListResponse.Data.models:type_name -> UserModel
	37, // 20: model_api.ModelSearchResponse.Data.models:type_name -> UserModel
	37, // 21: model_api.ModelGetResponse.Data.model:type_name -> UserModel
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_model_api_proto_init() }
func file_model_api_proto_init() {
	if File_model_api_proto != nil {
		return
	}
	file_model_base_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_model_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelTrainRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelTrainResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelPredictRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutlinePoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SliceOutLine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelPredictResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_api_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelSearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_api_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelSearchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_api_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_api_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_api_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_api_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_api_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelShareRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_api_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelShareResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_api_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelCreateResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_api_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelTrainResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_api_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelPredictResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_api_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelListResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_api_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelSearchResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_api_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelGetResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_api_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelDeleteResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_api_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelShareResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_model_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_api_proto_goTypes,
		DependencyIndexes: file_model_api_proto_depIdxs,
		MessageInfos:      file_model_api_proto_msgTypes,
	}.Build()
	File_model_api_proto = out.File
	file_model_api_proto_rawDesc = nil
	file_model_api_proto_goTypes = nil
	file_model_api_proto_depIdxs = nil
}
