// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.1
// source: model_config.proto

package model_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 网页配置
type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key          int32  `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Value        string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	DefaultValue int32  `protobuf:"varint,3,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_model_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_model_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetKey() int32 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *Config) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Config) GetDefaultValue() int32 {
	if x != nil {
		return x.DefaultValue
	}
	return 0
}

// 配置相关key对应的枚举项
type ConfigKeyEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   int32  `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ConfigKeyEnum) Reset() {
	*x = ConfigKeyEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigKeyEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigKeyEnum) ProtoMessage() {}

func (x *ConfigKeyEnum) ProtoReflect() protoreflect.Message {
	mi := &file_model_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigKeyEnum.ProtoReflect.Descriptor instead.
func (*ConfigKeyEnum) Descriptor() ([]byte, []int) {
	return file_model_config_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigKeyEnum) GetKey() int32 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *ConfigKeyEnum) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ConfigKeyEnumList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnumList []*ConfigKeyEnum `protobuf:"bytes,1,rep,name=enum_list,json=enumList,proto3" json:"enum_list,omitempty"`
}

func (x *ConfigKeyEnumList) Reset() {
	*x = ConfigKeyEnumList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_config_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigKeyEnumList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigKeyEnumList) ProtoMessage() {}

func (x *ConfigKeyEnumList) ProtoReflect() protoreflect.Message {
	mi := &file_model_config_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigKeyEnumList.ProtoReflect.Descriptor instead.
func (*ConfigKeyEnumList) Descriptor() ([]byte, []int) {
	return file_model_config_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigKeyEnumList) GetEnumList() []*ConfigKeyEnum {
	if x != nil {
		return x.EnumList
	}
	return nil
}

var File_model_config_proto protoreflect.FileDescriptor

var file_model_config_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x55, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x64,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x37, 0x0a, 0x0d, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4b, 0x65, 0x79, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x40, 0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4b, 0x65,
	0x79, 0x45, 0x6e, 0x75, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x09, 0x65, 0x6e, 0x75,
	0x6d, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4b, 0x65, 0x79, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x08, 0x65, 0x6e,
	0x75, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x1f, 0x5a, 0x1d, 0x2e, 0x2e, 0x2f, 0x2e, 0x2e, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x70, 0x62, 0x67, 0x65, 0x6e, 0x2f, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x5f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_model_config_proto_rawDescOnce sync.Once
	file_model_config_proto_rawDescData = file_model_config_proto_rawDesc
)

func file_model_config_proto_rawDescGZIP() []byte {
	file_model_config_proto_rawDescOnce.Do(func() {
		file_model_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_model_config_proto_rawDescData)
	})
	return file_model_config_proto_rawDescData
}

var file_model_config_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_model_config_proto_goTypes = []interface{}{
	(*Config)(nil),            // 0: Config
	(*ConfigKeyEnum)(nil),     // 1: ConfigKeyEnum
	(*ConfigKeyEnumList)(nil), // 2: ConfigKeyEnumList
}
var file_model_config_proto_depIdxs = []int32{
	1, // 0: ConfigKeyEnumList.enum_list:type_name -> ConfigKeyEnum
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_model_config_proto_init() }
func file_model_config_proto_init() {
	if File_model_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_model_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigKeyEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_config_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigKeyEnumList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_model_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_config_proto_goTypes,
		DependencyIndexes: file_model_config_proto_depIdxs,
		MessageInfos:      file_model_config_proto_msgTypes,
	}.Build()
	File_model_config_proto = out.File
	file_model_config_proto_rawDesc = nil
	file_model_config_proto_goTypes = nil
	file_model_config_proto_depIdxs = nil
}
